### ISSUE TITLE
GoAccess behind Traefik

### ISSUE THREAD

**Issue by SAOPP** [xavier-hernandez/goaccess-for-traefik#1]
Hi!

First of all, I want to express to u my gratitude for responding very quickly to my request for a parser for Traefik, it's incredible, I'm grateful. :+1: 

So I started to gaming with this, and got a first question, I trying to hide goaccess behind Traefik and faced with `Internal Server Error`.

Here is my stack:

```
  traefik-goaccess:
    image: xavierh/goaccess-for-traefik:develop
    container_name: traefik-goaccess
    hostname: traefik-goaccess
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - TZ=Europe/Kiev
      - SKIP_ARCHIVED_LOGS=False
    volumes:
      - ${DOCKER_HOST_PATH}/traefik/logs:/opt/log
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
    labels:
      - traefik.enable=true
      - traefik.http.services.proxy-logs.loadbalancer.server.port=7880
      - traefik.http.services.proxy-logs.loadbalancer.server.scheme=https
      - traefik.http.routers.proxy-logs.rule=Host(`${TRAEFIK_GOACCESS_HOST}.${DOMAIN}`)
      - traefik.http.routers.proxy-logs.entrypoints=websecure
      - traefik.http.routers.proxy-logs.tls=true
      - traefik.http.routers.proxy-logs.tls.certresolver=resolver
```
I’m not entirely sure that this is a 100% problem on the goaccess side, but I don’t see any problems with my deployment, the Traefik logs don’t say anything specific, the host receives a certificate and everything looks perfect, any thoughts on this? Thanks.
